name = "lukehoward-com"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "dist"

# Git repository configuration
[git]
repository = "git@github.com:libo/luke.git"
branch = "main"

# Custom domain configuration
[[pages.custom_domains]]
domain = "luke.cannici.eu"

# [[pages.custom_domains]]
# domain = "lukehoward.com"
